spring:
  datasource:
    url: jdbc:h2:mem:test
    driver-class-name: org.h2.Driver
    username: sa
  jpa:
    hibernate:
      ddl-auto: update
  flyway:
    enabled: false

# Invoice processor schedule
invoice-processor:
  restart:
    enabled: false
    cron-expression: '-'

integration:
  # Raindance integration
  raindance:
    environments:
      2281:
        host: someHost
        domain: HOME
        username: user
        password: p4ssw0rd
        share: mnt/Kivra/
        invoice-filename-prefixes:
          - Faktura
        batch-setup:
          "Faktura-pdf":
            scheduling:
              cron-expression: '-'
            process: true
            target-path: mnt/PN/
            archive-path: mnt/Kivra/Arkiv/
          "Betalningspaminnelse-pdf":
            scheduling:
              cron-expression: '-'
            process: false
            target-path: mnt/PN/
        connect-timeout: PT10S
        response-timeout: PT15S

  # Citizen
  citizen:
    url: http://something.com/citizen
    oauth2:
      token-url: http://something.com/token
      client-id: someClientId
      client-secret: someClientSecret

  # Party
  party:
    url: http://something.com/party
    oauth2:
      token-url: http://something.com/token
      client-id: someClientId
      client-secret: someClientSecret
  
  # Messaging
  messaging:
    connectTimeout: PT1S
    readTimeout: PT2S
    url: http://something.com/messaging
    token: someToken
    channel: someChannel
    oauth2:
      token-url: http://something.com/token
      client-id: someClientId
      client-secret: someClientSecret
    invoice:
      subject: someSubject
      reference-prefix: 'Faktura #'
    error-report:
      sender-name: SomeErrorSender
      sender-email-address: noreply.error@something.com
      recipient-email-addresses:
        - someone.error@something.com
      subject-prefix: someErrorPrefix
    status-report:
      sender-name: SomeStatusSender
      sender-email-address: noreply.status@something.com
      recipient-email-addresses:
        - someone.status@something.com
      subject-prefix: someStatusPrefix
