ALTER TABLE `batch_items` MODIFY COLUMN `status` enum('UNHANDLED', 'IGNORED', 'RECIPIENT_LEGAL_ID_FOUND','RECIPIENT_LEGAL_ID_NOT_FOUND_OR_INVALID','RECIPIENT_PARTY_ID_FOUND','RECIPIENT_PARTY_ID_NOT_FOUND','SENT','NOT_SENT') NOT NULL;
ALTER TABLE `batch_executions` ADD COLUMN `ignored_invoices` bigint(20) NOT NULL AFTER `total_invoices`;
