spring:
  datasource:
    url: jdbc:tc:mariadb:10.6:///it
    driver-class-name: org.testcontainers.jdbc.ContainerDatabaseDriver
  jpa:
    hibernate:
      ddl-auto: validate

integration:
  raindance:
    host: localhost
    port: 1139
    domain: HOME
    username: user
    password: p4ssw0rd
    share: mnt/
    local:
      unzip-work-directory: /tmp/it-raindance/unzip
      work-directory: /tmp/it-raindance/incoming

logging:
  level:
    org.testcontainers: INFO
