spring:
  datasource:
    url: jdbc:h2:mem:test
    driver-class-name: org.h2.Driver
    username: sa
  jpa:
    hibernate:
      ddl-auto: update
  flyway:
    enabled: false

integration:
  # Raindance
  raindance:
    host: localhost
    port: 1445
    domain: SOMEWORKGROUP
    username: user
    password: p4ssw0rd
    share: share
    work-directory: /tmp/raindance/incoming
    filename-prefixes:
      - Faktura-pdf
  
  # Party
  party:
    url: http://localhost:${wiremock.server.port}/party
    oauth2:
      token-url: http://localhost:${wiremock.server.port}/token
      client-id: someClientId
      client-secret: someClientSecret
  
  # Messaging
  messaging:
    url: http://localhost:${wiremock.server.port}/messaging
    oauth2:
      token-url: http://localhost:${wiremock.server.port}/token
      client-id: someClientId
      client-secret: someClientSecret
    invoice:
      subject: someSubject
      reference-prefix: 'Faktura #'
    status-report:
      sender-name: SomeSender
      sender-email-address: noreply@something.com
      recipient-email-addresses:
        - someone@something.com
      subject-prefix: somePrefix
