version: '3'
services:
  samba:
    image: dperson/samba
    ports:
      - "1445:445"
    tmpfs:
      - /tmp
    volumes:
      - ../../../target/test-classes/raindance-share:/files:rw
    command: -s "files;/files/;yes;no;no;user;user;user;none" -u "user;p4ssw0rd" -w SOMEWORKGROUP -p
