version: '3'
services:
  samba:
    image: dperson/samba
    ports:
      - "1445:445"
    tmpfs:
      - /tmp
    volumes:
      - ./raindance-share:/share:rw
    command: -s "share;/share/;yes;no;no;user;user;user;none" -u "user;p4ssw0rd" -w SOMEWORKGROUP -p
